### ISSUE TITLE
RPDE feed: 'modified' needs to be a timestamp

### ISSUE THREAD

**Issue by rhiaro** [openactive/conformance-services#101]
in the RPDE feed, `modified` is an ISO datetime. According to the spec, it SHOULD be an integer timestamp, but MUST match the `afterTimestamp` param in the `next` URL. We use the integer timestamp in for `afterTimestamp` so we should use it for `modified` as well.

> The modified property should contain either the modified timestamp or change number of the item, depending on the ordering strategy used. It MUST be appropriately comparable to itself as either a string or integer, representing a chronological ordering. It MUST always be updated when any data within <data> is updated, and such an update MUST set the value of the property to be greater than or equal to (>=) all existing modified values. It MAY be any format, but SHOULD be an integer where possible. Integer values MUST be represented as integers, not strings. The value of the modified property of the last item MUST be used in either the afterTimestamp or afterChangeNumber parameter of the "next" URL (though such an item may not be included in <items> if it is filtered out). **The format of the modified property and the relevant URL parameter MUST be identical.**

**Comment by odscjames** [comment]
Good catch, thanks

**Comment by rhiaro** [comment]
Fixed by #104
