### ISSUE TITLE
Database Indexes

### ISSUE THREAD

**Issue by odscjames** [openactive/conformance-services#105]
Adding some might help some queries.

**Comment by odscjames** [comment]
I tried 

    CREATE INDEX normalised_data_updated_at_data_id_idx ON normalised_data (updated_at, data_id);

first, as I was worried to make sure the web end point didn't have issues. According to EXPLAIN, postgres doesn't care and does a Parallel Seq Scan anyway!

**Comment by odscjames** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Database Indexes](https://trello.com/c/R6vJkg2L/85-database-indexes)

**Comment by michaelwood** [comment]
We added a bunch of useful indexes. See migrations for details.
