### ISSUE TITLE
Aggregate list of the 'top 10 errors'

### ISSUE THREAD

**Issue by nickevansuk** [openactive/conformance-services#16]
If you have already stored all errors that are returned, presenting an aggregate list of the 'top 10 errors' from the feeds of the dataset, and the number of occurrences of each, would be super!

**Comment by odscjames** [comment]
Sorry, wasn't watching and missed this.

I've started to discuss this for the output of the validation library in https://github.com/openactive/conformance-status-page/issues/4

**Comment by nickevansuk** [comment]
Suggest that discussion supersedes this one, as what you've suggested re: "Reorder by type of errors seen" is better.
