### ISSUE TITLE
Spidering Sources: Correctly handle the case where a dataset site itself is returning a 404

### ISSUE THREAD

**Issue by odscjames** [openactive/conformance-services#20]
From https://github.com/openactive/conformance-services/issues/18#issuecomment-648144547

> The dataset site itself is returning a 404 - The publisher has unpublished their data, and all data relating to that publisher should be purged immediately, in case of GDPR breach or similar (Note some systems such as Gladstone are designed to return a 404 from the dataset site if a user presses the "disable open data feeds" button within their booking system, so this is by design)

**Comment by odscjames** [comment]
See #39

**Comment by robredpath** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Establish what we need to do if a publisher stops publishing either a particular feed or OA data entirely](https://trello.com/c/Rj6Bfn4A/90-establish-what-we-need-to-do-if-a-publisher-stops-publishing-either-a-particular-feed-or-oa-data-entirely)

**Comment by robredpath** [comment]
Discussed with @thill-odi - see what the [spec](https://openactive.io/realtime-paged-data-exchange/#http-status-codes) has to say about HTTP codes

**Comment by robredpath** [comment]
We'll work on a takedown policy, which will address GDPR concerns
