### ISSUE TITLE
@openactive/data-model-validator -  loadRemoteJson and remoteJsonCachePath

### ISSUE THREAD

**Issue by odscjames** [openactive/conformance-services#22]
https://github.com/openactive/data-model-validator/blob/master/README.md

Should we be enabling loadRemoteJson?

If so we must enable remoteJsonCachePath or we'll start DOSing servers :-)

**Comment by nickevansuk** [comment]
Yes for sure, see config in https://github.com/openactive/openactive-test-suite/blob/master/packages/openactive-integration-tests/test/shared-behaviours/validation.js#L44 for reference

**Comment by odscjames** [comment]
Docs seem to suggest passing /tmp to remoteJsonCachePath, is that fine , or do we need to make a sub dir to avoid collisions?

Also has O,A. ever tried this on Heroku? From a quick Google it looks like Heroku server do have a /tmp dir that could be used.

**Comment by nickevansuk** [comment]
Good point, yep it's running on Heroku at http://validator.openactive.io/, via https://github.com/openactive/data-model-validator-site (see https://github.com/openactive/data-model-validator-site/blob/master/src/server/server.js#L310)
