### ISSUE TITLE
Documentation Format - which system?

### ISSUE THREAD

**Issue by odscjames** [openactive/conformance-services#30]
Previously we have created big README files, and we are starting another one.

Which system would you like to use for documentation?

I personally like a system in which the documentation is in the same repository as the code, as then during Pull Requests you can ensure that changes are made to both at the same time.

We normally use Sphinx and ReadTheDocs free hosting.

You can see a simple example of a simple docs/ folder at https://github.com/OpenDataServices/spreadsheet-forms/tree/master/docs

And the results are at https://spreadsheet-forms.readthedocs.io/en/latest/

**Comment by robredpath** [comment]
In my discussion with @thill-odi we agreed to use GitHub-based means of building docs - whether that's the GH wiki, GitBook, GH Pages (or whatever!), that's fine. 

As I understand it, you can configure GH pages to build from a `docs/` folder, so the workflow that you describe still works, without using an external build process @odscjames

**Comment by odscjames** [comment]
I'll rule out Wiki if I can, as that can't be checked in pull requests. Also we have already started using Wiki for spec notes.  I don't mind between GitBook or GH Pages (but with files in same repo is my preference).

**Comment by robredpath** [comment]
My preference is GH Pages - ruling out wiki for the same reason as you, and I can't immediately see any value added by using GitBook in this situation that we don't get from GH Pages.

**Comment by nickevansuk** [comment]
GH pages would fit with our other projects, most are documented by a set of markdown files in the repo, some of which are generated, all of which are linked together:
- https://github.com/openactive/data-model-validator
- https://github.com/openactive/openactive-test-suite
- https://github.com/openactive/skos.js
- https://github.com/openactive/OpenActive.NET

**Comment by nickevansuk** [comment]
GH pages would fit with our other projects, most are documented by a set of markdown files in the repo, some of which are generated, all of which are linked together:
- https://github.com/openactive/data-model-validator
- https://github.com/openactive/openactive-test-suite
- https://github.com/openactive/skos.js
- https://github.com/openactive/OpenActive.NET

We use the gh-pages model for our specs and other generated documentation:
- https://github.com/openactive/ns-beta
- https://github.com/openactive/openactive.github.io
- https://github.com/openactive/modelling-opportunity-data
- https://github.com/openactive/open-booking-api/

My personal preference would just be to generate Markdown into the repo unless we're talking about excessive complexity. If the docs aren't generated from the code, then just breaking out .md files in the repo would do.

**Comment by nickevansuk** [comment]
Most OpenActive projects are documented by a set of markdown files in the repo, some of which are generated, all of which are linked together:
- https://github.com/openactive/data-model-validator
- https://github.com/openactive/openactive-test-suite
- https://github.com/openactive/skos.js
- https://github.com/openactive/OpenActive.NET

We use the gh-pages model for our specs and other generated documentation, but not so much for libraries:
- https://github.com/openactive/ns-beta
- https://github.com/openactive/openactive.github.io
- https://github.com/openactive/modelling-opportunity-data
- https://github.com/openactive/open-booking-api/

My personal preference would just be to generate Markdown into the repo unless we're talking about excessive complexity. If the docs aren't generated from the code, then just breaking out .md files in the repo would do.

**Comment by michaelwood** [comment]
We've put everything in /docs and also setup a .gitbook.yaml in the root should you want to use gitbooks. [Example render](https://michaelwood.gitbook.io/openactive-conformance/)
