### ISSUE TITLE
When downloading raw data (harvesting) capture errors we encounter

### ISSUE THREAD

**Issue by odscjames** [openactive/conformance-services#40]

**Comment by odscjames** [comment]
New table: `download_raw_errors'

    URL - URL error occurred on
    Error - A code for the error; "HTTP_500" or "DNS" - this makes it easy to filter errors by a certain type.
    Message - A human readable message for the error
    At - time error occurred
    Publisher Feed - which feed we were working on when this happened

We can hold a lot of data in table; I'd suggest just starting with logging all errors. We can add something later to clean out old errors automatically

**Comment by odscjames** [comment]
Also see #21

**Comment by robredpath** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Capture errors during harvesting](https://trello.com/c/X0OUq4Hl/71-capture-errors-during-harvesting)

**Comment by odscjames** [comment]
Table and writing to it done. (Stuff on #21 not done, we'll deal with that there)
