### ISSUE TITLE
Make deletes cascade from source to normalised data

### ISSUE THREAD

**Issue by odscjames** [openactive/conformance-services#42]
See TODO in normalise_data_publisher_feed, src/lib/normalise-data.js

Wait for #41 tho, as that may complicate this slightly

**Comment by robredpath** [comment]
@odscjames what's the purpose of this issue? It seems to duplicate https://trello.com/c/2nIw5IhG/23-make-deletes-cascade-from-source-to-normalised-data but without any of the context

**Comment by robredpath** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Make deletes cascade from source to normalised data](https://trello.com/c/2nIw5IhG/23-make-deletes-cascade-from-source-to-normalised-data)

**Comment by rhiaro** [comment]
Given a piece of raw data that becomes `deleted`, we can look it up by the `raw_data_id` and `raw_data_parent_id` fields in `normalised_data`.

Todo: `raw_data_parent_id` does not exist yet.

**Comment by odscjames** [comment]
I would like to get #78 merged in then consider this alongside #79 as I think this and #79 may interact.

In fact possibly with the fix for #79, we can get the normalise pipeline to consider non-deleted items only and get rid of the store_deleted_callback function entirely.
