### ISSUE TITLE
Pipeline hangs sometimes

### ISSUE THREAD

**Issue by rhiaro** [openactive/conformance-services#50]
When running the pipeline with normalise-data.js, it passes 10 through then hangs, and none of the queries in the store_deleted_callback or store_normalised_callback are executed.

Limiting the publisher feed to specific feeds or a smaller number gives mixed results - some feeds pass a bunch of stuff through the pipes and the store callbacks are executed, before eventually hanging. Some hang immediately without trying to run the pipeline at all.

I haven't found any pattern to the data being processed when it hangs yet. It happens for deleted data or normalised data, and it happens if the data field is populated or null.

I suspect somewhere down the line a promise is not being properly handled, and something is stuck waiting for it forever.

Or it's something to do with the database.. May be related to #48?

**Comment by rhiaro** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Merge in a minimal set of real pipes to start getting the RPDE feed populated](https://trello.com/c/WQnzbyXc/81-merge-in-a-minimal-set-of-real-pipes-to-start-getting-the-rpde-feed-populated)

**Comment by odscjames** [comment]
I managed to get 3K items done after writing a P.R. for #48 - we'll need to look into this more

**Comment by odscjames** [comment]
@rhiaro says this works locally after the pull request so closing for now, will open again if we can recreate it.
