### ISSUE TITLE
Storing ids in raw_data

### ISSUE THREAD

**Issue by rhiaro** [openactive/conformance-services#55]
As mentioned in #51 we store the `id` field from the RPDE data as `data_id` in the raw data table.

When an event has a `superEvent` which is referenced rather than embedded, the value is typically a URL which would be found in the `id` or `@id` fields in the original data.

At the moment we can't fetch this easily from the database, because we don't extract and store the `id`/`@id` fields.

So we need a mini processing step during raw data storage that:

1. looks for `id`
2. if not found, looks for `@id`
3. if not found, looks for `identifier`
3.b) glues `identifier` onto the end of the feed url
4. Stores the value of 1, 2, or 3b in the data_id field of the database
5. If we still need the RPDE level id, suggest we store this as rpde_id or something

**Comment by rhiaro** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Normalisations](https://trello.com/c/C70upiyi/10-normalisations)

**Comment by odscjames** [comment]
Chatted

* Rename data_id field to rpde_id field and change existing code uses. Also rename raw_data_data_id constraint.
* Add new data_id field to raw_data, NOT NULL, unique constraint (data_id)
* Calculate this field as described above

Clarify: 3b feed_url is  publisher_feed.url  columumn in DB, not url of page item actually appears on (as that could change)

This means migrations will break for databases with existing data; but we have no live data so we don't care. Make sure to tell all team people tho at the point it's merged to master.
