### ISSUE TITLE
Error while running download-raw

### ISSUE THREAD

**Issue by odscjames** [openactive/conformance-services#87]
```

TypeError: Cannot read property '@id' of null
    at Function.getIdFromData (file:///home/app/src/lib/utils.js:46:21)
    at store_raw_callback (file:///home/app/src/lib/download-raw.js:39:38)
```

I only caught fragments as it went by but:

>  kind: 'league',
>    SportId: 6,
>       LeagueURL: 'https://www.gomammoth.co.uk/softball/regents-park/?leagueid=200',

**Comment by rhiaro** [comment]
I couldn't reproduce locally with the data from gomammoth I have, but added a test for this case then fixed it in #88
